---
- name: Deploy demo-app
  hosts: development
  vars:
    home_dir: "{{ ansible_env.HOME }}"
    project_name: demo-app
    venv_name: venv
    project_path: "{{ home_dir }}/{{ project_name }}"
    venv_path: "{{ home_dir }}/{{ project_name }}/{{ venv_name }}"
    repo_url: https://github.com/AlexPG/flask-demo-app.git
  tasks:

    - name: Update apt cache
      apt: 
        update_cache: yes
        cache_valid_time: 3600
      become: true

    - name: Install apt packages
      apt:
        name: "{{ item }}"
        state: latest
      become: true
      with_items:
        - build-essential
        - python-setuptools
        - python-dev
        - python-virtualenv
        - git
        - nginx
        - postgresql
        - python-psycopg2
        - libpq-dev
        - supervisor

    - name: Get project repo
      git:
        repo: "{{ repo_url }}"
        dest: "{{ project_path }}"
        force: yes

    - name: Install required python packages
      pip:
        name: "{{ item }}"
        virtualenv: "{{ venv_path }}"
        virtualenv_python: python2.7
      with_items:
        - gunicorn

    - name: Install requirements.txt
      pip:
        requirements: "{{ project_path }}/requirements.txt"
        virtualenv: "{{ venv_path }}"

    - name: Create postgresql user
      postgresql_user:
        name: vagrant
      become: true
      become_user: postgres

    - name: Create development database
      postgresql_db:
        name: data_dev
        owner: vagrant
        encoding: UTF8
      become: true
      become_user: postgres

    - name: Create test database
      postgresql_db:
        name: data_test
        owner: vagrant
        encoding: UTF8
      become: true
      become_user: postgres

    - name: Create demo-app tables
      command: "{{ venv_path }}/bin/python ./demo-app/manage.py createdb"

    - name: Set the gunicorn config file
      template: 
        src: templates/gunicorn_start.j2
        dest: "{{ venv_path }}/bin/gunicorn_start"
        mode: 0764

    - name: Set the supervisor config file
      template:
        src: templates/demoapp.conf.j2
        dest: /etc/supervisor/conf.d/demoapp.conf
      become: true
      notify: restart supervisor

    - name: Set the nginx config file
      template: 
        src: templates/demoapp.j2
        dest: /etc/nginx/sites-available/demoapp
      become: true
      notify: restart nginx
    
    - name: Remove the default nginx config file
      file: 
        path: /etc/nginx/sites-enabled/default 
        state: absent
      become: true
      notify: restart nginx

    - name: Enable the nginx config file
      file:
        src: /etc/nginx/sites-available/demoapp
        dest: /etc/nginx/sites-enabled/demoapp
        state: link
      become: true
      notify: restart nginx

  handlers:
    - name: restart supervisor
      supervisorctl: 
        name: demoapp 
        state: restarted
      become: True
    - name: restart nginx
      service: 
        name: nginx 
        state: restarted
      become: True
